### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by rafalohaki** [isooosi/VisVrs#23]
Would be possible to add headings/table of contents to articles on the right?

![image](https://github.com/isooosi/VisVrs/assets/20607107/c87c2a36-2f27-46e0-abeb-70a831191e33)

**Comment by isooosi** [comment]
Thank you for your valuable suggestion! 
We understand that a Table of Contents (TOC) is a helpful tool for quickly scanning and jumping to specific sections of an article. However, our design philosophy leans towards maintaining a clean page layout to encourage deep reading. We believe this offers a less distracted and more focused reading experience. 

We will continue to collect feedback from all users and consider balancing simplicity with functionality in future updates. Please stay tuned for our updates, and we look forward to providing you with an even better reading experience.

**Comment by isooosi** [comment]
Thank you for your valuable suggestion!
We understand that a Table of Contents (TOC) is a helpful tool for quickly scanning and jumping to specific sections of an article. However, our design philosophy leans towards maintaining a clean page layout to encourage deep reading. We believe this offers a less distracted and more focused reading experience.

We will continue to collect feedback from all users and consider balancing simplicity with functionality in future updates. Please stay tuned for our updates, and we look forward to providing you with an even better reading experience.
