### ISSUE TITLE
what about i18n

### ISSUE THREAD

**Issue by yakushevhk** [isooosi/VisVrs#45]
languages

**Comment by isooosi** [comment]
Thank you for your inquiry about internationalization (i18n) plans for our products. At the moment, we do not have a specific i18n strategy in place. Our current focus is on developing and enhancing our core features and services. However, we recognize the importance of internationalization and it remains an area of interest for future development. We appreciate your interest and will keep our users updated on any changes in this direction. Thank you for your understanding and support.
