### ISSUE TITLE
About cover picture file configuration problem

### ISSUE THREAD

**Issue by DerickIT** [isooosi/VisVrs#73]
After reviewing the code,` const socialImageURL = new URL(ogImage ? ogImage : '/open-graph. webp', Astro.url).href;`The cover image found is a relative path by default`src/images/visvrs1.webp`. What if I want to configure absolute addresses such as`https://www.notion.so/images/page-cover/rijksmuseum_jansz_1649.jpg`?

**Comment by isooosi** [comment]
🚀 The VisVrs has undergone a comprehensive upgrade. Please try the new version. v4.7
