### ISSUE TITLE
Dynamically set the category href within Header.astro

### ISSUE THREAD

**Issue by oregonpillow** [isooosi/VisVrs#74]
Currently, the category hrefs are hard coded within [Header.astro](https://github.com/isooosi/VisVrs/blob/502d1a6d721fff837081b7705c7bfb312c8a1844/src/components/Header.astro).
Would setting the hrefs dynamically make more sense?

For example, starting here: https://github.com/isooosi/VisVrs/blob/502d1a6d721fff837081b7705c7bfb312c8a1844/src/components/Header.astro#L10-L12 they are hard coded.

I'm completely new to astro/JS and this is the first template i've used. Love the design!

**Comment by oregonpillow** [comment]
I also noticed that https://github.com/isooosi/VisVrs/blob/502d1a6d721fff837081b7705c7bfb312c8a1844/src/components/Header.astro#L12C7-L12C65 is wrong anyway. Should be `<a href='/category/Three/1/' class='category-link'>Two</a>`

**Comment by isooosi** [comment]
The VisVrs has undergone a comprehensive upgrade. Please try the new version. v4.7.

**Comment by oregonpillow** [comment]
Hi thanks I've just had a look. I see that you extracted the code to the `consts.ts` file, but i don't see how this is better? 
It seems that you continue to hardcode the creation of HTML category links at top of page, but you've simply moved it to `consts.ts` 'HeaderLinks' variable?

With my solution, any category specified in the markdown front matter dynamically gets a category link created for it. No need to hardcode html for them. Done.

I don't understand why you dynamically create links everywhere else, but for arguably the most prominent and important links on the site you have them hard coded?

Am i missing something??
