### ISSUE TITLE
Content duplication

### ISSUE THREAD

**Issue by DerickIT** [isooosi/VisVrs#78]
Click the page number button from the first page to the second page, and the content is repeated, for example, the last three items on the first page are also displayed on the second page.
page 1
![image](https://github.com/isooosi/VisVrs/assets/20416202/953b60ae-bb5b-4e3c-b919-27461b39db20)
page 2
![image](https://github.com/isooosi/VisVrs/assets/20416202/a81b3a03-da7c-4d05-9783-3ae3fecaf390)

**Comment by isooosi** [comment]
Fixed  pagination calculation logic error
